### PR TITLE
Remove duplicate vendor/ in .gitignore

### PR DESCRIPTION
**Pull request by johnnypeck**
Remove duplicate vendor/ in .gitignore

### CODE REVIEW

**Comment by sergiors** [comment]
Thanks @johnnypeck 🎉🎉🎉🎉🎉

**Comment by sergiors** [comment]
@johnnypeck your website is offline

**Comment by johnnypeck** [comment]
Thanks. I'm aware of that.

@johnnypeck https://github.com/johnnypeck your website is offline

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/sergiors/mapping/pull/1#issuecomment-227175216, or mute
the thread
https://github.com/notifications/unsubscribe/AAPjmzjKfhzxiM08p-BJzCNTJGIqW78Jks5qNrBegaJpZM4I5d2M
.

**Comment by sergiors** [comment]
@johnnypeck do you use mapping project for solve some problem?
I'm using with doctrine to restore the POPO (`array_json`), but I need to do the way when is `object -> json` (persiste)

**Pull request merged**
